package com.example.MicroInvestApp.domain.enums;

public enum ContentCategory {
    INVESTING_BASICS,
    CAPITAL_MARKETS,
    INVESTMENT_STRATEGIES,
    BEHAVIORAL_FINANCE,
    RISK_MANAGEMENT,
    PORTFOLIO_MANAGEMENT,
    FINANCIAL_ANALYSIS,
    MARKET_TRENDS,
    CRYPTOCURRENCY,
    REAL_ESTATE,
    RETIREMENT_PLANNING,
    TAX_STRATEGIES
}
